name: 'Code Coverage Cobertura'
description: 'Coverage expert by cobertura'
inputs:
  filename:
    description: 'Report to Cobertura Coverage XML Report'
    required: true
  min_coverage:
    description: 'Coverage percent (minimum to enforce)'
    required: false
    default: 80
  fail_if_low:
    description: 'Whether to fail the build if coverage too low.'
    required: false
    default: false
outputs:
  percent:
    description: 'Current coverage percentage'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.filename }}
    - ${{ inputs.min_coverage }}
    - ${{ inputs.fail_if_low }}
