name: PHPUnit
run-name: PHPUnit Testing
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:
jobs:
  phpunit:
    name: Build Test Server
    runs-on: ubuntu-latest
#    environment: testing
    strategy:
      fail-fast: true
      matrix:
        php: [8.1]
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: phpunit-bridge
          extensions: mbstring, xml, ctype, iconv, pdo_sqlite, json, opcache, mysql, mcrypt, zip, simplexml, gd, bcmath, intl, dom, soap
          coverage: xdebug

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Create Composer Cache
        id: cache-composer
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: php-${{ matrix.php }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: php-${{ matrix.php }}-composer-

      - if: ${{ steps.cache-composer.outputs.cache-hit != 'true' }}
        name: List the State of Composer Modules
        continue-on-error: true
        run: composer show

      - name: Install Composer Dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Run PHPUnit Tests
        run: |
          php vendor/bin/phpunit -c phpunit.xml.dist tests \
            --coverage-text=output/tests/coverage.txt \
            --coverage-clover=output/tests/coverage.clover.xml \
            --coverage-cobertura=output/tests/coverage.cobertura.xml \
            --log-junit=output/tests/report.junit.xml

      - name: PHPUnit Coverage Report Plain
        if: always()
        run: cat output/tests/coverage.txt

      - name: PHPUnit Coverage Report Cobertura
        uses: irongut/CodeCoverageSummary@v1.3.0
        if: always()
        with:
          filename: output/tests/coverage.cobertura.xml
          badge: true
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'

      - name: PHPUnit Coverage Report Clover
        uses: sourcetoad/phpunit-coverage-action@v1
        if: always()
        with:
          clover_report_path: output/tests/coverage.clover.xml
          min_coverage_percent: 80
          fail_build_on_under: false

      - name: PHPUnit Coverage Report Clover 2
        uses: actions/phpunit-cobertura/action.yml
        if: always()
        with:
          clover_report_path: output/tests/coverage.txt
          min_coverage_percent: 85
          fail_build_on_under: false

      - name: Publish PHPUnit Result
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: View PHPUnit Result
          files: output/tests/report.junit.xml
